version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    env_file: 
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - jogomemoria-network
  
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    depends_on:
      - postgres
    env_file: 
      - .env
    ports:
      - "8081:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - jogomemoria-network

  jogomemoria-backend:
    image: edsonisaac/jogomemoria-backend:latest
    restart: unless-stopped
    depends_on:
      - postgres
      - pgadmin
    env_file: 
      - .env
    ports:
      - "8080:8080"
    volumes:
      - jogomemoria-backend-data:/var/lib/jogomemoria-backend
    networks:
      - jogomemoria-network
  
  jogomemoria-frontend:
    image: edsonisaac/jogomemoria-frontend:latest
    restart: unless-stopped
    depends_on:
      - postgres
      - pgadmin
      - jogomemoria-backend
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - jogomemoria-frontend-data:/var/lib/jogomemoria-frontend
    networks:
      - jogomemoria-network

volumes:
  postgres-data:
  pgadmin-data:
  jogomemoria-backend-data:
  jogomemoria-frontend-data:

networks:
  jogomemoria-network:
    driver: bridge